"""empty message

Revision ID: b310e547a431
Revises: None
Create Date: 2017-10-27 18:29:22.220655

"""

# revision identifiers, used by Alembic.
revision = 'b310e547a431'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pandas_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pandas_db',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('MD_EARN_WNE_P10', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('C150_4', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('DEBT_MDN_SUPP', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LOAN_EVER', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('INSTNM', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Tuition', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('IND_DEBT_MDN', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('FIRSTGEN_DEBT_MDN', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('NOTFIRSTGEN_DEBT_MDN', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
